apiVersion: v1
kind: Service
metadata:
  name: flask-backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: { { .Values.backend.port } }
      targetPort: { { .Values.backend.port } }
  type: ClusterIP
